# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/metadata-syntax-for-github-actions
name: 'Build and deploy Segment Sloth Functions'
description: 'Automatically deploy your functions from your Segment Sloth as a Github Action'
author: 'Christy Haragan (https://github.com/christyharagan/sloth-github-action)'
runs:
  using: 'node12'
  main: 'out/index.js'
branding:
  color: 'green'
  icon: 'command'
inputs:
  segment-access-token:
    description: 'Workspace access token. Requires function admin privileges.'
    required: false
  segment-workspace-slug:
    description: 'Workspace slug'
    required: false
  segment-workspace-id:
    description: 'Workspace ID'
    required: false